name: Build and Test

on:
  # schedule:
  #   - cron: '0 10 * * 0'
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'deployment/**'
      - '.github/**'
  pull_request:


jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Install Dependencies
      run: |
        go mod download

    - name: Build
      run: |
        go build -o app .

    - name: Test
      run: |
        go test -v ./...